In [34]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

In [35]:
df = pd.read_excel("iris.xls")
df

sepal length  sepal width  petal length  petal width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [36]:
X = df.iloc[:,:4].values
Y = df.iloc[:,4].values

Veri setini train ve test olarak bölelim

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.33, random_state=0)

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Hangi classification algoritması daha iyi? Tek tek model inşa edip karşılaştıralım.

In [41]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train)

pred_logr = logr.predict(X_test)

con_matrix = confusion_matrix(y_test,pred_logr)
con_matrix

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  2, 13]])

In [42]:
#K-Nearest neighborhood
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric="minkowski")
knn.fit(X_train,y_train)

pred_knn = knn.predict(X_test)

con_matrix = confusion_matrix(y_test,pred_knn)
con_matrix

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

In [43]:
#SVC
from sklearn.svm import SVC
svc = SVC(kernel="rbf")
svc.fit(X_train,y_train)

pred_svc = svc.predict(X_test)

con_matrix = confusion_matrix(y_test,pred_svc)
con_matrix

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

In [44]:
#Naive bayes (Gaussian bayes kullanmak istedim. Diğerleri de kullanılabilir.)
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

pred_bayes = gnb.predict(X_test)

con_matrix = confusion_matrix(y_test,pred_bayes)
con_matrix

array([[16,  0,  0],
       [ 0, 19,  0],
       [ 0,  2, 13]])

In [45]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
tree_c = DecisionTreeClassifier(criterion="entropy")
tree_c.fit(X_train, y_train)

pred_tree = tree_c.predict(X_test)

con_matrix = confusion_matrix(y_test,pred_tree)
con_matrix

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

In [46]:
#Random forest
from sklearn.ensemble import RandomForestClassifier
forest_c = RandomForestClassifier(n_estimators=10, criterion="entropy")
forest_c.fit(X_train, y_train)

pred_forest = forest_c.predict(X_test)

con_matrix = confusion_matrix(y_test,pred_forest)
con_matrix

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

Tüm algoritmalara bakınca logistic ressionda 3 diğerlerinde 2 şer hata yapıldığını görüyoruz. Parametreleri değiştirdiğimiz taktirde bu hataların azalacağı ve artacağı görülüyor. O yüzden bu örneğin şimdiki halinde şu algoritma en iyisidir diyemiyorum. 